packages:
  - docs

ignoreWorkspaceRootCheck: true

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3
  - sharp
  - simple-git-hooks

packageManagerStrict: false

shellEmulator: true

verifyDepsBeforeRun: install
