packages:
  - docs

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'

onlyBuiltDependencies:
  - better-sqlite3
  - sharp

shellEmulator: true
ignoreWorkspaceRootCheck: true
packageManagerStrict: false
