ignoreWorkspaceRootCheck: true

shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3 # https://github.com/paulmillr/chokidar/issues/1440
  - semver@6.3.1
  - oxc-parser/binding-win32-x64-msvc@0.81.0
  - oxc-parser/binding-win32-arm64-msvc@0.81.0
  - oxc-parser/binding-linux-x64-gnu@0.81.0
  - oxc-parser/binding-linux-x64-musl@0.81.0
  - oxc-parser/binding-linux-arm64-gnu@0.81.0
  - oxc-parser/binding-linux-arm-gnueabihf@0.81.0
  - oxc-parser/binding-linux-arm64-musl@0.81.0
  - oxc-parser/binding-darwin-x64@0.81.0
  - oxc-parser/binding-darwin-arm64@0.81.0
  - oxc-parser/binding-wasm32-wasi@0.81.0
  - '@oxc-transform/binding-win32-x64-msvc@0.81.0'
  - '@oxc-transform/binding-win32-arm64-msvc@0.81.0'
  - '@oxc-transform/binding-linux-x64-gnu@0.81.0'
  - '@oxc-transform/binding-linux-x64-musl@0.81.0'
  - '@oxc-transform/binding-linux-arm64-gnu@0.81.0'
  - '@oxc-transform/binding-linux-arm-gnueabihf@0.81.0'
  - '@oxc-transform/binding-linux-arm64-musl@0.81.0'
  - '@oxc-transform/binding-darwin-x64@0.81.0'
  - '@oxc-transform/binding-darwin-arm64@0.81.0'
  - '@oxc-transform/binding-wasm32-wasi@0.81.0'
  - '@oxc-parser/binding-win32-x64-msvc@0.81.0'
  - '@oxc-parser/binding-win32-arm64-msvc@0.81.0'
  - '@oxc-parser/binding-linux-x64-gnu@0.81.0'
  - '@oxc-parser/binding-linux-x64-musl@0.81.0'
  - '@oxc-parser/binding-linux-arm64-gnu@0.81.0'
  - '@oxc-parser/binding-linux-arm-gnueabihf@0.81.0'
  - '@oxc-parser/binding-linux-arm64-musl@0.81.0'
  - '@oxc-parser/binding-darwin-x64@0.81.0'
  - '@oxc-parser/binding-darwin-arm64@0.81.0'
  - '@oxc-parser/binding-wasm32-wasi@0.81.0'

  # provenance was added from v0.11.0 this is backport security fix
  # ref. https://www.npmjs.com/package/synckit?activeTab=versions
  - synckit@0.9.3

  # provenance for v6 is introduced from v6.23+
  # ref. https://github.com/nodejs/undici/issues/4666
  - undici-types@6.21.0

  # avoid no-downgrade check against usage of @vueuse/integrations@14 in docs workspace
  # ref. https://github.com/elk-zone/elk/pull/3441
  - '@vueuse/integrations@13.9.0'
packages:
  - docs

overrides:
  nuxt-component-meta: 0.17.2
  serialize-javascript: 7.0.5
  unstorage: ^1.17.5
  vitest: 4.1.8
  vue: ^3.5.4

verifyDepsBeforeRun: install

allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  better-sqlite3: true
  esbuild: false
  sharp: true
  simple-git-hooks: true
  vue-demi: false
