ignoreWorkspaceRootCheck: true

packageManagerStrict: false

shellEmulator: true

trustPolicy: no-downgrade

packages:
  - docs

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3
  - sharp
  - simple-git-hooks

verifyDepsBeforeRun: install
