declare module 'twitter-text/dist/regexp' {
    const regexen = {
        astralLetterAndMarks: RegExp,
        astralNumerals: RegExp,
        atSigns: RegExp,
        bmpLetterAndMarks: RegExp,
        bmpNumerals: RegExp,
        cashtag: RegExp,
        codePoint: RegExp,
        cyrillicLettersAndMarks: RegExp,
        endHashtagMatch: RegExp,
        endMentionMatch: RegExp,
        extractUrl: RegExp,
        hashSigns: RegExp,
        hashtagAlpha: RegExp,
        hashtagAlphaNumeric: RegExp,
        hashtagBoundary: RegExp,
        hashtagSpecialChars: RegExp,
        invalidChars: RegExp,
        invalidCharsGroup: RegExp,
        invalidDomainChars: RegExp,
        invalidUrlWithoutProtocolPrecedingChars: RegExp,
        latinAccentChars: RegExp,
        nonBmpCodePairs: RegExp,
        punct: RegExp,
        rtlChars: RegExp,
        spaces: RegExp,
        spacesGroup: RegExp,
        urlHasHttps: RegExp,
        urlHasProtocol: RegExp,
        validAsciiDomain: RegExp,
        validateUrlAuthority: RegExp,
        validateUrlDecOctet: RegExp,
        validateUrlDomain: RegExp,
        validateUrlDomainSegment: RegExp,
        validateUrlDomainTld: RegExp,
        validateUrlFragment: RegExp,
        validateUrlHost: RegExp,
        validateUrlIp: RegExp,
        validateUrlIpv4: RegExp,
        validateUrlIpv6: RegExp,
        validateUrlPath: RegExp,
        validateUrlPchar: RegExp,
        validateUrlPctEncoded: RegExp,
        validateUrlPort: RegExp,
        validateUrlQuery: RegExp,
        validateUrlScheme: RegExp,
        validateUrlSubDelims: RegExp,
        validateUrlSubDomainSegment: RegExp,
        validateUrlUnencoded: RegExp,
        validateUrlUnicodeAuthority: RegExp,
        validateUrlUnicodeDomain: RegExp,
        validateUrlUnicodeDomainSegment: RegExp,
        validateUrlUnicodeDomainTld: RegExp,
        validateUrlUnicodeHost: RegExp,
        validateUrlUnicodeSubDomainSegment: RegExp,
        validateUrlUnreserved: RegExp,
        validateUrlUserinfo: RegExp,
        validCashtag: RegExp,
        validCCTLD: RegExp,
        validDomain: RegExp,
        validDomainChars: RegExp,
        validDomainName: RegExp,
        validGeneralUrlPathChars: RegExp,
        validGTLD: RegExp,
        validHashtag: RegExp,
        validMentionOrList: RegExp,
        validMentionPrecedingChars: RegExp,
        validPortNumber: RegExp,
        validPunycode: RegExp,
        validReply: RegExp,
        validSubdomain: RegExp,
        validTcoUrl: RegExp,
        validUrlBalancedParens: RegExp,
        validUrlPath: RegExp,
        validUrlPathEndingChars: RegExp,
        validUrlPrecedingChars: RegExp,
        validUrlQueryChars: RegExp,
        validUrlQueryEndingChars: RegExp,
    }
    export = regexen
}

declare module 'twitter-text/dist/lib/regexSupplant' {
    export function regexSupplant(regex: RegEx | string, map: object, flags: string)
    export = regexSupplant
}