name: 🐞 Bug report
description: Report an issue
labels: ['s: pending triage', 'c: bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        If you are unsure whether your problem is a bug or not, you can check the following:

        - use our [Discord community](https://chat.elk.zone)
        - open a new [discussion](https://github.com/elk-zone/elk/discussions) and ask your question there

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Pre-Checks
      description: Before submitting the issue, please make sure you do the following
      options:
        # - label: Follow our [Code of Conduct](https://github.com/elk-zone/elk/blob/main/CODE_OF_CONDUCT.md).
        #   required: true
        # - label: Read the [Contributing Guidelines](https://github.com/elk-zone/elk/blob/main/CONTRIBUTING.md).
        #   required: true
        - label: Check that there isn't [already an issue](https://github.com/elk-zone/elk/issues) that reports the same bug to avoid creating a duplicate.
          required: true
        - label: Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/elk-zone/elk/discussions) or join our [Discord Chat Server](https://chat.elk.zone).
          required: true
        - label: Providing a screenshot or video to reproduce the issue or show visually what was meant.
          required: true
        - label: I am willing to provide a PR.

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: I am doing ... What I expect is ... What actually happening is ...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction video or screenshot
      description: |
        A video or screenshot that visually shows the issue.
        **Tip:** You can attach images or recordings files by clicking this area to highlight it and then dragging files in.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Anything else relevant? Please tell us here, e.g. your used web browser and/or you are on desktop or mobile.
        **Tip:** You can attach images or recordings files by clicking this area to highlight it and then dragging files in.
