blank_issues_enabled: false
contact_links:
  - name: Discord Chat
    url: https://chat.elk.zone
    about: Ask questions and discuss with other users in real time.
  - name: Questions & Discussions
    url: https://github.com/elk-zone/elk/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
